# ==========================================
# 1. CẤU HÌNH SERVER & APPLICATION
# ==========================================
server.port=8080
spring.application.name=api-gateway

# ==========================================
# 2. CẤU HÌNH KEYCLOAK (CHẠY TRONG DOCKER)
# ==========================================
# - Tên miền: dùng tên service 'keycloak'
# - Port: dùng port nội bộ 8080 (chứ không phải 8081 map ra ngoài host)
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/food-delivery-realm
# ==========================================
# 3. CẤU HÌNH ROUTES (ĐỊNH TUYẾN GATEWAY)
# ==========================================

# Route 0: Đẩy tất cả API Auth về User Service (Keycloak)
spring.cloud.gateway.routes[0].id=user-module
spring.cloud.gateway.routes[0].uri=http://keycloak:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/realms/**

# Route 1: Đẩy tất cả API Promotions về Voucher Service
spring.cloud.gateway.routes[1].id=voucher-module
# Sử dụng tên service 'voucher-module' và port nội bộ 8082
spring.cloud.gateway.routes[1].uri=http://voucher-module:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/v1/promotions/**

# Route 2: Đẩy tất cả API Đơn hàng về Order Service (Java)
spring.cloud.gateway.routes[2].id=order-module
spring.cloud.gateway.routes[2].uri=http://order-module:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/v1/orders/**

# Route 3: Đẩy tất cả API Restaurant về Restaurant Service (C# .NET)
spring.cloud.gateway.routes[3].id=restaurant-module
spring.cloud.gateway.routes[3].uri=http://restaurant-module:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/restaurant/**